- hosts: 192.168.50.101
  become: false
  gather_facts: false
  tasks:

  - name: Create new vm with minimal options
    vars:
      ansible_python_interpreter: /usr/bin/python3
    proxmox_kvm:
      api_user: '{{api_user}}'
      api_token_id: '{{api_token_id}}'
      api_token_secret: '{{api_token_secret}}'
#      api_user: ansible@pam
#      api_token_id: ansible_token
#      api_token_secret: 5009c78c-4ff3-4dbc-96ec-0838861abc69
      api_host: 192.168.50.101
      node: pve1
      name: vmtest2
